### ISSUE TITLE
Rework of Env

### ISSUE THREAD

**Issue by stheid** [upb-lea/openmodelica-microgrid-gym#45]
- [x] All values in ABC
- [x] Reference in the Environent #43
- [x] Normalize actions #44 
- [x] Normalize states
- [x] Update standard agents to be capable of denormalization

The referenced issues showed that a general overhaul of the environment interface is needed in order to allow general RL agents to learn on it properly

The new environment will provide normalized states including reference information. Everything voltage and current will be in ABC.
The actions expected by the environment are normalized as well.

It remains to be seen if an stateless RL agent can act well on ABC data, but for now it seems like a good path. Maybe it makes sense to keep the idea to switch to DQ0 using only an option in the env in mind.

**Comment by stheid** [comment]
Status quo:

reference in dq0 in the agent
state is in abc and returned by the env
actions to the env are also in abc

-> we just need to change the reference to abc and put it into the env.

**Comment by stheid** [comment]
- An environment is a network.
- A network consists of components. Components are "loads" and "inverters".
- An inverter can take two roles: 'master', 'slave'.
- a master inverter has:
    - out: a voltage and current setpoint
    - out: a voltage and current measurement
    - in: gets modulation gain for DC-link-voltage 
    - the current setpoint can be 0.
    - one setpoint, measurement and action per phase.
	- all in all this means 3 inputs and 12 outputs
- a slave inverter is similar,
    - except it does not have a voltage setpoint
	- this means 3 inputs and 9 outputs
- a load has:
    - [right now] one current for each phase 
	     (in a stable net this is also a proximate power, as the voltage aproximates the setpoint voltage)
	- [later] power

**Comment by stheid** [comment]
the network could be specified in the following yaml syntax.
commented lines are defaults that can be ommited alltogether.
Values are normalized to 0,1, therefore voltage setpoint is actually not needed.

```
net:
  inv1:
    id: lc1
    cls: MasterInverter
    u: [i1p1,...]    # names of the inputs
    v:
    - capacitor1.v
    - capacitor2.v    # <- alternative yaml array syntax
    - capacitor3.v
    i: [inductor1.i,...]
    # iref: [0,0,0]
    # vref: [1,0,0]
  inv2:
   ...
   ...
  load:
     id: rl1
     cls: Load
     i: [...]
```

The environment will provides a list of key words that can be map to the state output values. for example. if we do not specify the iref here in the configuration, the env will still return the abc references and they are named "inv1.iref1" ... However, yaml may not preserve order, therefore the agent needs to know how to map the values that are provided in the state as np.array to the values that it has to stick into its internal controllers. Right now we have the "obs_templates" for that and we probably only need to update them slightly to be able to work with the new structure of values.
